// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AccountQuery {
    /**
     * Creates a new AccountQuery instance.
     * @param {Partial<AccountQuery>} [$$source = {}] - The source object to create the AccountQuery.
     */
    constructor($$source = {}) {
        if (!("search" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["search"] = "";
        }
        if (!("account_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["account_type"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }
        if (!("active_only" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active_only"] = false;
        }
        if (!("sort_by" in $$source)) {
            /**
             * id | account_type | last_refresh | email
             * @member
             * @type {string}
             */
            this["sort_by"] = "";
        }
        if (!("sort_order" in $$source)) {
            /**
             * asc | desc
             * @member
             * @type {string}
             */
            this["sort_order"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountQuery instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountQuery}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountQuery(/** @type {Partial<AccountQuery>} */($$parsedSource));
    }
}

/**
 * AccountResponse is the DTO returned to the frontend.
 */
export class AccountResponse {
    /**
     * Creates a new AccountResponse instance.
     * @param {Partial<AccountResponse>} [$$source = {}] - The source object to create the AccountResponse.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("codex_password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["codex_password"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("refresh_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["refresh_token"] = "";
        }
        if (!("last_refresh_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_refresh_time"] = "";
        }
        if (!("account_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["account_type"] = "";
        }
        if (!("remark" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }
        if (!("is_active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_active"] = false;
        }
        if (!("days_since_refresh" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["days_since_refresh"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountResponse(/** @type {Partial<AccountResponse>} */($$parsedSource));
    }
}

export class AccountTypeResponse {
    /**
     * Creates a new AccountTypeResponse instance.
     * @param {Partial<AccountTypeResponse>} [$$source = {}] - The source object to create the AccountTypeResponse.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountTypeResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountTypeResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountTypeResponse(/** @type {Partial<AccountTypeResponse>} */($$parsedSource));
    }
}

export class AccountsResponse {
    /**
     * Creates a new AccountsResponse instance.
     * @param {Partial<AccountsResponse>} [$$source = {}] - The source object to create the AccountsResponse.
     */
    constructor($$source = {}) {
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {AccountResponse[]}
             */
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountsResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountsResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new AccountsResponse(/** @type {Partial<AccountsResponse>} */($$parsedSource));
    }
}

export class CLIProxyAPIStats {
    /**
     * Creates a new CLIProxyAPIStats instance.
     * @param {Partial<CLIProxyAPIStats>} [$$source = {}] - The source object to create the CLIProxyAPIStats.
     */
    constructor($$source = {}) {
        if (!("total_requests" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_requests"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_tokens"] = 0;
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: CLIProxyModelStats }}
             */
            this["models"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIProxyAPIStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CLIProxyAPIStats}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField2_0($$parsedSource["models"]);
        }
        return new CLIProxyAPIStats(/** @type {Partial<CLIProxyAPIStats>} */($$parsedSource));
    }
}

export class CLIProxyAuthFile {
    /**
     * Creates a new CLIProxyAuthFile instance.
     * @param {Partial<CLIProxyAuthFile>} [$$source = {}] - The source object to create the CLIProxyAuthFile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("auth_index" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["auth_index"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("status_message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status_message"] = "";
        }
        if (!("disabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["disabled"] = false;
        }
        if (!("unavailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["unavailable"] = false;
        }
        if (!("runtime_only" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["runtime_only"] = false;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["email"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["account_type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["account"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["created_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["updated_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_refresh"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["next_retry_after"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["priority"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["note"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIProxyAuthFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CLIProxyAuthFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CLIProxyAuthFile(/** @type {Partial<CLIProxyAuthFile>} */($$parsedSource));
    }
}

export class CLIProxyAuthFilesResult {
    /**
     * Creates a new CLIProxyAuthFilesResult instance.
     * @param {Partial<CLIProxyAuthFilesResult>} [$$source = {}] - The source object to create the CLIProxyAuthFilesResult.
     */
    constructor($$source = {}) {
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {CLIProxyAuthFile[]}
             */
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIProxyAuthFilesResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CLIProxyAuthFilesResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        return new CLIProxyAuthFilesResult(/** @type {Partial<CLIProxyAuthFilesResult>} */($$parsedSource));
    }
}

export class CLIProxyConfig {
    /**
     * Creates a new CLIProxyConfig instance.
     * @param {Partial<CLIProxyConfig>} [$$source = {}] - The source object to create the CLIProxyConfig.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIProxyConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CLIProxyConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CLIProxyConfig(/** @type {Partial<CLIProxyConfig>} */($$parsedSource));
    }
}

export class CLIProxyModelStats {
    /**
     * Creates a new CLIProxyModelStats instance.
     * @param {Partial<CLIProxyModelStats>} [$$source = {}] - The source object to create the CLIProxyModelStats.
     */
    constructor($$source = {}) {
        if (!("total_requests" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_requests"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_tokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIProxyModelStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CLIProxyModelStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CLIProxyModelStats(/** @type {Partial<CLIProxyModelStats>} */($$parsedSource));
    }
}

export class CLIProxyStatus {
    /**
     * Creates a new CLIProxyStatus instance.
     * @param {Partial<CLIProxyStatus>} [$$source = {}] - The source object to create the CLIProxyStatus.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("stats_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["stats_enabled"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIProxyStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CLIProxyStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CLIProxyStatus(/** @type {Partial<CLIProxyStatus>} */($$parsedSource));
    }
}

export class CLIProxyUsage {
    /**
     * Creates a new CLIProxyUsage instance.
     * @param {Partial<CLIProxyUsage>} [$$source = {}] - The source object to create the CLIProxyUsage.
     */
    constructor($$source = {}) {
        if (!("total_requests" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_requests"] = 0;
        }
        if (!("success_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["success_count"] = 0;
        }
        if (!("failure_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failure_count"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_tokens"] = 0;
        }
        if (!("requests_by_day" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: number }}
             */
            this["requests_by_day"] = {};
        }
        if (!("tokens_by_day" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: number }}
             */
            this["tokens_by_day"] = {};
        }
        if (!("apis" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: CLIProxyAPIStats }}
             */
            this["apis"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIProxyUsage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CLIProxyUsage}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType6;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("requests_by_day" in $$parsedSource) {
            $$parsedSource["requests_by_day"] = $$createField4_0($$parsedSource["requests_by_day"]);
        }
        if ("tokens_by_day" in $$parsedSource) {
            $$parsedSource["tokens_by_day"] = $$createField5_0($$parsedSource["tokens_by_day"]);
        }
        if ("apis" in $$parsedSource) {
            $$parsedSource["apis"] = $$createField6_0($$parsedSource["apis"]);
        }
        return new CLIProxyUsage(/** @type {Partial<CLIProxyUsage>} */($$parsedSource));
    }
}

export class CheckAllResult {
    /**
     * Creates a new CheckAllResult instance.
     * @param {Partial<CheckAllResult>} [$$source = {}] - The source object to create the CheckAllResult.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("alive" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alive"] = 0;
        }
        if (!("dead" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dead"] = 0;
        }
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {CheckResult[]}
             */
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckAllResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckAllResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField3_0($$parsedSource["results"]);
        }
        return new CheckAllResult(/** @type {Partial<CheckAllResult>} */($$parsedSource));
    }
}

/**
 * CheckResult holds the liveness result for a single account.
 */
export class CheckResult {
    /**
     * Creates a new CheckResult instance.
     * @param {Partial<CheckResult>} [$$source = {}] - The source object to create the CheckResult.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("alive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alive"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CheckResult(/** @type {Partial<CheckResult>} */($$parsedSource));
    }
}

export class CodexConfig {
    /**
     * Creates a new CodexConfig instance.
     * @param {Partial<CodexConfig>} [$$source = {}] - The source object to create the CodexConfig.
     */
    constructor($$source = {}) {
        if (!("proxy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxy"] = "";
        }
        if (!("oauth_client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["oauth_client_id"] = "";
        }
        if (!("oauth_redirect_uri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["oauth_redirect_uri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodexConfig(/** @type {Partial<CodexConfig>} */($$parsedSource));
    }
}

export class CodexOAuthResult {
    /**
     * Creates a new CodexOAuthResult instance.
     * @param {Partial<CodexOAuthResult>} [$$source = {}] - The source object to create the CodexOAuthResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("json" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["json"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexOAuthResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexOAuthResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodexOAuthResult(/** @type {Partial<CodexOAuthResult>} */($$parsedSource));
    }
}

export class CreateAccountRequest {
    /**
     * Creates a new CreateAccountRequest instance.
     * @param {Partial<CreateAccountRequest>} [$$source = {}] - The source object to create the CreateAccountRequest.
     */
    constructor($$source = {}) {
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("codex_password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["codex_password"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("refresh_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["refresh_token"] = "";
        }
        if (!("account_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["account_type"] = "";
        }
        if (!("remark" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateAccountRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateAccountRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateAccountRequest(/** @type {Partial<CreateAccountRequest>} */($$parsedSource));
    }
}

export class CreateTypeRequest {
    /**
     * Creates a new CreateTypeRequest instance.
     * @param {Partial<CreateTypeRequest>} [$$source = {}] - The source object to create the CreateTypeRequest.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTypeRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateTypeRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateTypeRequest(/** @type {Partial<CreateTypeRequest>} */($$parsedSource));
    }
}

export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["success"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("errors" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

export class MailDetail {
    /**
     * Creates a new MailDetail instance.
     * @param {Partial<MailDetail>} [$$source = {}] - The source object to create the MailDetail.
     */
    constructor($$source = {}) {
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("body_text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body_text"] = "";
        }
        if (!("body_html" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body_html"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MailDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MailDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MailDetail(/** @type {Partial<MailDetail>} */($$parsedSource));
    }
}

export class MailDetailResponse {
    /**
     * Creates a new MailDetailResponse instance.
     * @param {Partial<MailDetailResponse>} [$$source = {}] - The source object to create the MailDetailResponse.
     */
    constructor($$source = {}) {
        if (!("account_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["account_id"] = 0;
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("folder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folder"] = "";
        }
        if (!("message_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message_id"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {MailDetail}
             */
            this["detail"] = (new MailDetail());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MailDetailResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MailDetailResponse}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("detail" in $$parsedSource) {
            $$parsedSource["detail"] = $$createField4_0($$parsedSource["detail"]);
        }
        return new MailDetailResponse(/** @type {Partial<MailDetailResponse>} */($$parsedSource));
    }
}

export class MailItem {
    /**
     * Creates a new MailItem instance.
     * @param {Partial<MailItem>} [$$source = {}] - The source object to create the MailItem.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("folder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folder"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MailItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MailItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MailItem(/** @type {Partial<MailItem>} */($$parsedSource));
    }
}

export class MailListResponse {
    /**
     * Creates a new MailListResponse instance.
     * @param {Partial<MailListResponse>} [$$source = {}] - The source object to create the MailListResponse.
     */
    constructor($$source = {}) {
        if (!("account_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["account_id"] = 0;
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("folder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folder"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {MailItem[]}
             */
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MailListResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MailListResponse}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField6_0($$parsedSource["items"]);
        }
        return new MailListResponse(/** @type {Partial<MailListResponse>} */($$parsedSource));
    }
}

export class RefreshAllResult {
    /**
     * Creates a new RefreshAllResult instance.
     * @param {Partial<RefreshAllResult>} [$$source = {}] - The source object to create the RefreshAllResult.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["success"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("errors" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RefreshAllResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RefreshAllResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new RefreshAllResult(/** @type {Partial<RefreshAllResult>} */($$parsedSource));
    }
}

export class SyncResult {
    /**
     * Creates a new SyncResult instance.
     * @param {Partial<SyncResult>} [$$source = {}] - The source object to create the SyncResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncResult(/** @type {Partial<SyncResult>} */($$parsedSource));
    }
}

export class UpdateAccountRequest {
    /**
     * Creates a new UpdateAccountRequest instance.
     * @param {Partial<UpdateAccountRequest>} [$$source = {}] - The source object to create the UpdateAccountRequest.
     */
    constructor($$source = {}) {
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("codex_password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["codex_password"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("refresh_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["refresh_token"] = "";
        }
        if (!("account_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["account_type"] = "";
        }
        if (!("remark" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }
        if (!("is_active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateAccountRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateAccountRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateAccountRequest(/** @type {Partial<UpdateAccountRequest>} */($$parsedSource));
    }
}

export class UpdateTypeRequest {
    /**
     * Creates a new UpdateTypeRequest instance.
     * @param {Partial<UpdateTypeRequest>} [$$source = {}] - The source object to create the UpdateTypeRequest.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateTypeRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateTypeRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateTypeRequest(/** @type {Partial<UpdateTypeRequest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AccountResponse.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = CLIProxyModelStats.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = CLIProxyAuthFile.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = CLIProxyAPIStats.createFrom;
const $$createType8 = $Create.Map($Create.Any, $$createType7);
const $$createType9 = CheckResult.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = MailDetail.createFrom;
const $$createType13 = MailItem.createFrom;
const $$createType14 = $Create.Array($$createType13);
