// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AccountQuery {
    /**
     * Creates a new AccountQuery instance.
     * @param {Partial<AccountQuery>} [$$source = {}] - The source object to create the AccountQuery.
     */
    constructor($$source = {}) {
        if (!("search" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["search"] = "";
        }
        if (!("account_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["account_type"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }
        if (!("active_only" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active_only"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountQuery instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountQuery}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountQuery(/** @type {Partial<AccountQuery>} */($$parsedSource));
    }
}

/**
 * AccountResponse is the DTO returned to the frontend.
 */
export class AccountResponse {
    /**
     * Creates a new AccountResponse instance.
     * @param {Partial<AccountResponse>} [$$source = {}] - The source object to create the AccountResponse.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("refresh_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["refresh_token"] = "";
        }
        if (!("last_refresh_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_refresh_time"] = "";
        }
        if (!("account_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["account_type"] = "";
        }
        if (!("remark" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }
        if (!("is_active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_active"] = false;
        }
        if (!("days_since_refresh" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["days_since_refresh"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountResponse(/** @type {Partial<AccountResponse>} */($$parsedSource));
    }
}

export class AccountTypeResponse {
    /**
     * Creates a new AccountTypeResponse instance.
     * @param {Partial<AccountTypeResponse>} [$$source = {}] - The source object to create the AccountTypeResponse.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountTypeResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountTypeResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountTypeResponse(/** @type {Partial<AccountTypeResponse>} */($$parsedSource));
    }
}

export class AccountsResponse {
    /**
     * Creates a new AccountsResponse instance.
     * @param {Partial<AccountsResponse>} [$$source = {}] - The source object to create the AccountsResponse.
     */
    constructor($$source = {}) {
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {AccountResponse[]}
             */
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountsResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountsResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new AccountsResponse(/** @type {Partial<AccountsResponse>} */($$parsedSource));
    }
}

export class CheckAllResult {
    /**
     * Creates a new CheckAllResult instance.
     * @param {Partial<CheckAllResult>} [$$source = {}] - The source object to create the CheckAllResult.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("alive" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alive"] = 0;
        }
        if (!("dead" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dead"] = 0;
        }
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {CheckResult[]}
             */
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckAllResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckAllResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField3_0($$parsedSource["results"]);
        }
        return new CheckAllResult(/** @type {Partial<CheckAllResult>} */($$parsedSource));
    }
}

/**
 * CheckResult holds the liveness result for a single account.
 */
export class CheckResult {
    /**
     * Creates a new CheckResult instance.
     * @param {Partial<CheckResult>} [$$source = {}] - The source object to create the CheckResult.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("alive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alive"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CheckResult(/** @type {Partial<CheckResult>} */($$parsedSource));
    }
}

export class CreateAccountRequest {
    /**
     * Creates a new CreateAccountRequest instance.
     * @param {Partial<CreateAccountRequest>} [$$source = {}] - The source object to create the CreateAccountRequest.
     */
    constructor($$source = {}) {
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("refresh_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["refresh_token"] = "";
        }
        if (!("account_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["account_type"] = "";
        }
        if (!("remark" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateAccountRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateAccountRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateAccountRequest(/** @type {Partial<CreateAccountRequest>} */($$parsedSource));
    }
}

export class CreateTypeRequest {
    /**
     * Creates a new CreateTypeRequest instance.
     * @param {Partial<CreateTypeRequest>} [$$source = {}] - The source object to create the CreateTypeRequest.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTypeRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateTypeRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateTypeRequest(/** @type {Partial<CreateTypeRequest>} */($$parsedSource));
    }
}

export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["success"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("errors" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

export class MailDetail {
    /**
     * Creates a new MailDetail instance.
     * @param {Partial<MailDetail>} [$$source = {}] - The source object to create the MailDetail.
     */
    constructor($$source = {}) {
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("body_text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body_text"] = "";
        }
        if (!("body_html" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body_html"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MailDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MailDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MailDetail(/** @type {Partial<MailDetail>} */($$parsedSource));
    }
}

export class MailDetailResponse {
    /**
     * Creates a new MailDetailResponse instance.
     * @param {Partial<MailDetailResponse>} [$$source = {}] - The source object to create the MailDetailResponse.
     */
    constructor($$source = {}) {
        if (!("account_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["account_id"] = 0;
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("folder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folder"] = "";
        }
        if (!("message_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message_id"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {MailDetail}
             */
            this["detail"] = (new MailDetail());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MailDetailResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MailDetailResponse}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("detail" in $$parsedSource) {
            $$parsedSource["detail"] = $$createField4_0($$parsedSource["detail"]);
        }
        return new MailDetailResponse(/** @type {Partial<MailDetailResponse>} */($$parsedSource));
    }
}

export class MailItem {
    /**
     * Creates a new MailItem instance.
     * @param {Partial<MailItem>} [$$source = {}] - The source object to create the MailItem.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("folder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folder"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MailItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MailItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MailItem(/** @type {Partial<MailItem>} */($$parsedSource));
    }
}

export class MailListResponse {
    /**
     * Creates a new MailListResponse instance.
     * @param {Partial<MailListResponse>} [$$source = {}] - The source object to create the MailListResponse.
     */
    constructor($$source = {}) {
        if (!("account_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["account_id"] = 0;
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("folder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folder"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {MailItem[]}
             */
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MailListResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MailListResponse}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField6_0($$parsedSource["items"]);
        }
        return new MailListResponse(/** @type {Partial<MailListResponse>} */($$parsedSource));
    }
}

export class RefreshAllResult {
    /**
     * Creates a new RefreshAllResult instance.
     * @param {Partial<RefreshAllResult>} [$$source = {}] - The source object to create the RefreshAllResult.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["success"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("errors" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RefreshAllResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RefreshAllResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new RefreshAllResult(/** @type {Partial<RefreshAllResult>} */($$parsedSource));
    }
}

export class UpdateAccountRequest {
    /**
     * Creates a new UpdateAccountRequest instance.
     * @param {Partial<UpdateAccountRequest>} [$$source = {}] - The source object to create the UpdateAccountRequest.
     */
    constructor($$source = {}) {
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("refresh_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["refresh_token"] = "";
        }
        if (!("account_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["account_type"] = "";
        }
        if (!("remark" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }
        if (!("is_active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateAccountRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateAccountRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateAccountRequest(/** @type {Partial<UpdateAccountRequest>} */($$parsedSource));
    }
}

export class UpdateTypeRequest {
    /**
     * Creates a new UpdateTypeRequest instance.
     * @param {Partial<UpdateTypeRequest>} [$$source = {}] - The source object to create the UpdateTypeRequest.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateTypeRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateTypeRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateTypeRequest(/** @type {Partial<UpdateTypeRequest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AccountResponse.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = CheckResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = MailDetail.createFrom;
const $$createType6 = MailItem.createFrom;
const $$createType7 = $Create.Array($$createType6);
