// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MailService is the Wails service exposing all app methods to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function ArchiveAccount(id) {
    return $Call.ByID(702183999, id);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ArchiveAllAccounts() {
    return $Call.ByID(480840959);
}

/**
 * CheckAllAccounts tries to refresh the OAuth token for every active account
 * concurrently (max 10 goroutines) and returns alive/dead status for each.
 * @returns {$CancellablePromise<models$0.CheckAllResult>}
 */
export function CheckAllAccounts() {
    return $Call.ByID(1137080409).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {models$0.CreateAccountRequest} req
 * @returns {$CancellablePromise<models$0.AccountResponse>}
 */
export function CreateAccount(req) {
    return $Call.ByID(93127665, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {models$0.CreateTypeRequest} req
 * @returns {$CancellablePromise<models$0.AccountTypeResponse>}
 */
export function CreateAccountType(req) {
    return $Call.ByID(4162112185, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAccount(id) {
    return $Call.ByID(1528268380, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAccountType(id) {
    return $Call.ByID(1390154516, id);
}

/**
 * DeleteDeadAccounts deletes all accounts whose IDs are in the provided list.
 * @param {number[]} ids
 * @returns {$CancellablePromise<number>}
 */
export function DeleteDeadAccounts(ids) {
    return $Call.ByID(1694362403, ids);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ExportAccounts() {
    return $Call.ByID(3409337020);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<models$0.AccountResponse>}
 */
export function GetAccount(id) {
    return $Call.ByID(2136391657, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.AccountTypeResponse[]>}
 */
export function GetAccountTypes() {
    return $Call.ByID(1237512214).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {models$0.AccountQuery} query
 * @returns {$CancellablePromise<models$0.AccountsResponse>}
 */
export function GetAccounts(query) {
    return $Call.ByID(261070702, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {number} accountID
 * @param {string} folder
 * @param {string} messageID
 * @returns {$CancellablePromise<models$0.MailDetailResponse>}
 */
export function GetMailDetail(accountID, folder, messageID) {
    return $Call.ByID(3818970004, accountID, folder, messageID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {number} accountID
 * @param {string} folder
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<models$0.MailListResponse>}
 */
export function GetMails(accountID, folder, page, pageSize) {
    return $Call.ByID(3016250402, accountID, folder, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ImportAccounts parses lines in format: email----password----client_id----refresh_token
 * @param {string} text
 * @returns {$CancellablePromise<models$0.ImportResult>}
 */
export function ImportAccounts(text) {
    return $Call.ByID(170311267, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.RefreshAllResult>}
 */
export function RefreshAllTokens() {
    return $Call.ByID(1526491722).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function RefreshToken(id) {
    return $Call.ByID(2301194854, id);
}

/**
 * @param {number} id
 * @param {models$0.UpdateAccountRequest} req
 * @returns {$CancellablePromise<models$0.AccountResponse>}
 */
export function UpdateAccount(id, req) {
    return $Call.ByID(2975065014, id, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} id
 * @param {models$0.UpdateTypeRequest} req
 * @returns {$CancellablePromise<models$0.AccountTypeResponse>}
 */
export function UpdateAccountType(id, req) {
    return $Call.ByID(967191974, id, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.CheckAllResult.createFrom;
const $$createType1 = models$0.AccountResponse.createFrom;
const $$createType2 = models$0.AccountTypeResponse.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.AccountsResponse.createFrom;
const $$createType5 = models$0.MailDetailResponse.createFrom;
const $$createType6 = models$0.MailListResponse.createFrom;
const $$createType7 = models$0.ImportResult.createFrom;
const $$createType8 = models$0.RefreshAllResult.createFrom;
